#!/usr/bin/env python3

import argparse
 
parser = argparse.ArgumentParser()
parser.add_argument('filename', type=argparse.FileType('r'))

args = parser.parse_args()

programCode = args.filename.readlines()
executable = ""
print(f'UwU! wunning youw scwipt: {args.filename.name}\n\n')
for l in programCode:
    line = l
    line = line.replace("pwint(", "print(")
    line = line.replace("vawiabwe ", "")
    line = line.replace("fuwunction ", "def ")
    line = line.replace("wetuwn ", "return ")
    line = line.replace("owpen(", "open(")
    line = line.replace("wange(", "range(")
    line = line.replace("fow ", "for ")
    line = line.replace("whiwe ", "while ")
    line = line.replace(".stwip()", ".strip()")
    line = line.replace("Twue", "True")
    line = line.replace("{", ":")
    line = line.replace("}", "")
    line = line.replace(".intewpwet()", ".readlines()")
    
    executable += line

exec(executable)